import "./test-config-setup";
import { strict as assert } from "assert";
import { mkdtempSync, mkdirSync, writeFileSync, unlinkSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { saveConfig } from "./src/config";
import { workspacePolicy, readPage, OUTPUT_BYTES } from "./src/workspace";
import { globFiles, grepFiles, listDir } from "./src/tools/executor";
import { expandSelection, expandFileMentions, readFilesAsContext } from "./src/files";
import { buildIndex } from "./src/indexer";
import { fitContext } from "./src/llm";

const root = mkdtempSync(join(tmpdir(), "ccli-context-"));
saveConfig({ cwd: root, contextWindow: 8192, autoCompact: true, maxTokens: 1024 });
function file(path: string, text: string) { writeFileSync(join(root, path), text); }
for (const dir of ["src", "build", "generated", "src/cache"]) mkdirSync(join(root, dir), { recursive: true });
file(".gitignore", "generated/\n*.log\n/root-only.txt\n");
file(".localcliignore", "!keep.log\n");
file("src/.gitignore", "cache/\n");
file("src/a.ts", "export function alpha() { return 1; }");
file("build/out.ts", "export function generatedBuild() {}");
file("generated/out.ts", "export function generatedCode() {}");
file("src/cache/cache.ts", "export function cacheCode() {}");
file("root-only.txt", "hidden"); file("src/root-only.txt", "visible");
file("keep.log", "visible"); file("other.log", "hidden");
const excluded = workspacePolicy(root);
assert(excluded(join(root, "generated/out.ts")));
assert(excluded(join(root, "src/cache/cache.ts")));
assert(!excluded(join(root, "keep.log")));
assert(!excluded(join(root, "src/root-only.txt")));
const listing = await globFiles({ pattern: "**/*" });
assert(!listing.includes("out.ts") && !listing.includes("cache.ts") && listing.includes("keep.log"));
assert((await globFiles({ pattern: "build/**", include_ignored: true })).includes("out.ts"));
assert(!listDir({}).includes("d build"));
assert(!expandSelection([root], root).some(p => p.includes("out.ts")));
file("huge.txt", "line\n".repeat(1000000) + "UNIQUE_NEEDLE\n");
const page = readPage(join(root, "huge.txt"));
assert(Buffer.byteLength(page) <= OUTPUT_BYTES && page.includes("offset=201"));
assert(readPage(join(root, "huge.txt"), 999999, 3).includes("UNIQUE_NEEDLE"));
assert((await grepFiles({ pattern: "UNIQUE_NEEDLE", path: "huge.txt" })).includes("1000001:UNIQUE_NEEDLE"));
file("long.txt", "x".repeat(1000000));
assert(Buffer.byteLength(readPage(join(root, "long.txt"))) <= OUTPUT_BYTES);
assert(readPage(join(root, "long.txt")).includes("do not edit"));
assert(expandFileMentions("check @huge.txt", root).includes("Large file"));
assert(!expandFileMentions("check @huge.txt", root).includes("UNIQUE_NEEDLE"));
assert(Buffer.byteLength(readFilesAsContext([join(root, "huge.txt"), join(root, "long.txt")], root).block) <= OUTPUT_BYTES);
let index = await buildIndex();
assert(index.symbols.some(s => s.name === "alpha") && !index.symbols.some(s => s.name.includes("generated")));
file("src/a.ts", "export function betaChanged() { return 200; }");
index = await buildIndex();
assert(index.symbols.some(s => s.name === "betaChanged") && !index.symbols.some(s => s.name === "alpha"));
unlinkSync(join(root, "src/a.ts"));
assert(!(await buildIndex()).symbols.some(s => s.name === "betaChanged"));
file(".localcliignore", "!keep.log\nsrc/\n");
assert(!(await globFiles({ pattern: "**/*" })).includes("src/root-only.txt"));
const history: any[] = [{ role: "system", content: "help" }, { role: "user", content: "Find the issue" }, { role: "assistant", content: null, tool_calls: [{ id: "a", type: "function", function: { name: "read_file", arguments: "{}" } }] }, { role: "tool", tool_call_id: "a", content: "x".repeat(100000) }];
assert(await fitContext(history));
assert(history[3].tool_call_id === "a" && history[1].content === "Find the issue");
assert(!(await fitContext([{ role: "user", content: "x".repeat(100000) }])));
console.log("Context limits passed: ignores, overrides, million-line reads/search, huge lines, attachments, index refresh, context guard.");
